# Write a program to input eight numbers from the user and display all the unique numbers (once).

numbers=set()
s1=int(input("Enter number 1: "))
numbers.add(s1)
s2=int(input("Enter number 2: "))           
numbers.add(s2)
s3=int(input("Enter number 3: "))
numbers.add(s3)
s4=int(input("Enter number 4: "))
numbers.add(s4)
s5=int(input("Enter number 5: "))
numbers.add(s5)
s6=int(input("Enter number 6: "))
numbers.add(s6)
s7=int(input("Enter number 7: "))
numbers.add(s7)
s8=int(input("Enter number 8: "))
numbers.add(s8)
print("The unique numbers are:", numbers)